FROM openjdk:17-jdk-slim

WORKDIR /app

# Копируем исходный код
COPY . .

# Собираем проект (замените на вашу команду сборки)
RUN ./gradlew build

EXPOSE 8080 4573

ENTRYPOINT ["java", "-jar", "*.jar"]